"""initial schema

Revision ID: d053db13cc38
Revises: 
Create Date: 2026-08-07 15:40:13.986442
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd053db13cc38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_item_id'), 'alerts', ['item_id'], unique=False)
    op.create_index(op.f('ix_alerts_sent_at'), 'alerts', ['sent_at'], unique=False)
    op.create_table('click_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('subscriber_id', sa.String(length=36), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('ab_group', sa.String(length=1), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_click_events_issue_id'), 'click_events', ['issue_id'], unique=False)
    op.create_index(op.f('ix_click_events_kind'), 'click_events', ['kind'], unique=False)
    op.create_index(op.f('ix_click_events_subscriber_id'), 'click_events', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_click_events_week'), 'click_events', ['week'], unique=False)
    op.create_table('event_sources_resolved',
    sa.Column('source_id', sa.String(length=20), nullable=False),
    sa.Column('listing_url', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('needs_manual_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('promoter', sa.String(length=255), nullable=False),
    sa.Column('organiser', sa.String(length=255), nullable=False),
    sa.Column('detail_url', sa.Text(), nullable=False),
    sa.Column('programme_url', sa.Text(), nullable=False),
    sa.Column('source_urls', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('event_format', sa.String(length=20), nullable=False),
    sa.Column('stated_audience', sa.Text(), nullable=False),
    sa.Column('programme_evidence', sa.JSON(), nullable=False),
    sa.Column('pls_fit', sa.String(length=20), nullable=False),
    sa.Column('ecm_accredited', sa.Boolean(), nullable=True),
    sa.Column('ecm_credits', sa.String(length=60), nullable=False),
    sa.Column('accredited_professions', sa.JSON(), nullable=False),
    sa.Column('registration_status', sa.String(length=120), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('early_registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('fee', sa.String(length=120), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('why_relevant', sa.Text(), nullable=False),
    sa.Column('is_national_pls_congress', sa.Boolean(), nullable=False),
    sa.Column('dedup_key', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_dedup_key'), 'events', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_events_pls_fit'), 'events', ['pls_fit'], unique=False)
    op.create_index(op.f('ix_events_source_id'), 'events', ['source_id'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('subscriber_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('too_long', sa.Boolean(), nullable=False),
    sa.Column('too_many_devices', sa.Boolean(), nullable=False),
    sa.Column('not_relevant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedback_issue_id'), 'feedback', ['issue_id'], unique=False)
    op.create_table('news_items',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_country', sa.String(length=10), nullable=False),
    sa.Column('source_reliability', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('access_limited', sa.Boolean(), nullable=False),
    sa.Column('geo', sa.String(length=10), nullable=False),
    sa.Column('taxonomy_tags', sa.JSON(), nullable=False),
    sa.Column('setting', sa.String(length=20), nullable=False),
    sa.Column('pls_relevance', sa.Float(), nullable=False),
    sa.Column('device_related', sa.Boolean(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('subscores', sa.JSON(), nullable=False),
    sa.Column('penalties', sa.JSON(), nullable=False),
    sa.Column('transferability', sa.Float(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('headline_operational', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('what_to_do', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('key_passages', sa.JSON(), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_role', sa.String(length=50), nullable=True),
    sa.Column('review_reason', sa.String(length=80), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('unsupported_claims', sa.JSON(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_news_items_canonical_url'), 'news_items', ['canonical_url'], unique=True)
    op.create_index(op.f('ix_news_items_source_key'), 'news_items', ['source_key'], unique=False)
    op.create_table('newsletters',
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('subject_line', sa.Text(), nullable=False),
    sa.Column('preheader', sa.Text(), nullable=False),
    sa.Column('ab_element', sa.String(length=20), nullable=False),
    sa.Column('ab_variant_b', sa.Text(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('tldr', sa.JSON(), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_newsletters_status'), 'newsletters', ['status'], unique=False)
    op.create_index(op.f('ix_newsletters_week'), 'newsletters', ['week'], unique=False)
    op.create_table('review_decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('edits', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_review_decisions_issue_id'), 'review_decisions', ['issue_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_item_id'), 'review_decisions', ['item_id'], unique=False)
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirm_token', sa.String(length=64), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('alert_opt_in', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('ab_group', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('subscriber_id')
    )
    op.create_index(op.f('ix_subscribers_ab_group'), 'subscribers', ['ab_group'], unique=False)
    op.create_index(op.f('ix_subscribers_confirm_token'), 'subscribers', ['confirm_token'], unique=True)
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_subscribers_status'), 'subscribers', ['status'], unique=False)
    op.create_index(op.f('ix_subscribers_unsubscribe_token'), 'subscribers', ['unsubscribe_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_unsubscribe_token'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_status'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_confirm_token'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_ab_group'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_review_decisions_item_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_issue_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_newsletters_week'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_status'), table_name='newsletters')
    op.drop_table('newsletters')
    op.drop_index(op.f('ix_news_items_source_key'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_canonical_url'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_feedback_issue_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_source_id'), table_name='events')
    op.drop_index(op.f('ix_events_pls_fit'), table_name='events')
    op.drop_index(op.f('ix_events_dedup_key'), table_name='events')
    op.drop_table('events')
    op.drop_table('event_sources_resolved')
    op.drop_index(op.f('ix_click_events_week'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_subscriber_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_kind'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_issue_id'), table_name='click_events')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_alerts_sent_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_item_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
