"""add rules_version

Revision ID: f415afb31625
Revises: 9b50a0fc750b
Create Date: 2026-08-08 20:17:37.798495
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f415afb31625'
down_revision: Union[str, None] = '9b50a0fc750b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('rules_version', sa.String(length=20), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_items', 'rules_version')
    # ### end Alembic commands ###
